# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/james/miniconda3/envs/mpich/lib/python3.7/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/james/miniconda3/envs/mpich/lib/python3.7/site-packages/cmake/data/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/james/apps/pull_requests/Dice

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/james/apps/pull_requests/Dice

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/james/miniconda3/envs/mpich/lib/python3.7/site-packages/cmake/data/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/home/james/miniconda3/envs/mpich/lib/python3.7/site-packages/cmake/data/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/james/miniconda3/envs/mpich/lib/python3.7/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/james/apps/pull_requests/Dice/CMakeFiles /home/james/apps/pull_requests/Dice/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/james/apps/pull_requests/Dice/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_determinants

# Build rule for target.
test_determinants: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_determinants
.PHONY : test_determinants

# fast build rule for target.
test_determinants/fast:
	$(MAKE) -f CMakeFiles/test_determinants.dir/build.make CMakeFiles/test_determinants.dir/build
.PHONY : test_determinants/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named eigen_project

# Build rule for target.
eigen_project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eigen_project
.PHONY : eigen_project

# fast build rule for target.
eigen_project/fast:
	$(MAKE) -f CMakeFiles/eigen_project.dir/build.make CMakeFiles/eigen_project.dir/build
.PHONY : eigen_project/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named Dice

# Build rule for target.
Dice: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Dice
.PHONY : Dice

# fast build rule for target.
Dice/fast:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/build
.PHONY : Dice/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

Davidson.o: Davidson.cpp.o

.PHONY : Davidson.o

# target to build an object file
Davidson.cpp.o:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/Davidson.cpp.o
.PHONY : Davidson.cpp.o

Davidson.i: Davidson.cpp.i

.PHONY : Davidson.i

# target to preprocess a source file
Davidson.cpp.i:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/Davidson.cpp.i
.PHONY : Davidson.cpp.i

Davidson.s: Davidson.cpp.s

.PHONY : Davidson.s

# target to generate assembly for a file
Davidson.cpp.s:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/Davidson.cpp.s
.PHONY : Davidson.cpp.s

Determinants.o: Determinants.cpp.o

.PHONY : Determinants.o

# target to build an object file
Determinants.cpp.o:
	$(MAKE) -f CMakeFiles/test_determinants.dir/build.make CMakeFiles/test_determinants.dir/Determinants.cpp.o
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/Determinants.cpp.o
.PHONY : Determinants.cpp.o

Determinants.i: Determinants.cpp.i

.PHONY : Determinants.i

# target to preprocess a source file
Determinants.cpp.i:
	$(MAKE) -f CMakeFiles/test_determinants.dir/build.make CMakeFiles/test_determinants.dir/Determinants.cpp.i
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/Determinants.cpp.i
.PHONY : Determinants.cpp.i

Determinants.s: Determinants.cpp.s

.PHONY : Determinants.s

# target to generate assembly for a file
Determinants.cpp.s:
	$(MAKE) -f CMakeFiles/test_determinants.dir/build.make CMakeFiles/test_determinants.dir/Determinants.cpp.s
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/Determinants.cpp.s
.PHONY : Determinants.cpp.s

LCC.o: LCC.cpp.o

.PHONY : LCC.o

# target to build an object file
LCC.cpp.o:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/LCC.cpp.o
.PHONY : LCC.cpp.o

LCC.i: LCC.cpp.i

.PHONY : LCC.i

# target to preprocess a source file
LCC.cpp.i:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/LCC.cpp.i
.PHONY : LCC.cpp.i

LCC.s: LCC.cpp.s

.PHONY : LCC.s

# target to generate assembly for a file
LCC.cpp.s:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/LCC.cpp.s
.PHONY : LCC.cpp.s

SHCI.o: SHCI.cpp.o

.PHONY : SHCI.o

# target to build an object file
SHCI.cpp.o:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCI.cpp.o
.PHONY : SHCI.cpp.o

SHCI.i: SHCI.cpp.i

.PHONY : SHCI.i

# target to preprocess a source file
SHCI.cpp.i:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCI.cpp.i
.PHONY : SHCI.cpp.i

SHCI.s: SHCI.cpp.s

.PHONY : SHCI.s

# target to generate assembly for a file
SHCI.cpp.s:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCI.cpp.s
.PHONY : SHCI.cpp.s

SHCISortMpiUtils.o: SHCISortMpiUtils.cpp.o

.PHONY : SHCISortMpiUtils.o

# target to build an object file
SHCISortMpiUtils.cpp.o:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCISortMpiUtils.cpp.o
.PHONY : SHCISortMpiUtils.cpp.o

SHCISortMpiUtils.i: SHCISortMpiUtils.cpp.i

.PHONY : SHCISortMpiUtils.i

# target to preprocess a source file
SHCISortMpiUtils.cpp.i:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCISortMpiUtils.cpp.i
.PHONY : SHCISortMpiUtils.cpp.i

SHCISortMpiUtils.s: SHCISortMpiUtils.cpp.s

.PHONY : SHCISortMpiUtils.s

# target to generate assembly for a file
SHCISortMpiUtils.cpp.s:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCISortMpiUtils.cpp.s
.PHONY : SHCISortMpiUtils.cpp.s

SHCIbasics.o: SHCIbasics.cpp.o

.PHONY : SHCIbasics.o

# target to build an object file
SHCIbasics.cpp.o:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCIbasics.cpp.o
.PHONY : SHCIbasics.cpp.o

SHCIbasics.i: SHCIbasics.cpp.i

.PHONY : SHCIbasics.i

# target to preprocess a source file
SHCIbasics.cpp.i:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCIbasics.cpp.i
.PHONY : SHCIbasics.cpp.i

SHCIbasics.s: SHCIbasics.cpp.s

.PHONY : SHCIbasics.s

# target to generate assembly for a file
SHCIbasics.cpp.s:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCIbasics.cpp.s
.PHONY : SHCIbasics.cpp.s

SHCIgetdeterminants.o: SHCIgetdeterminants.cpp.o

.PHONY : SHCIgetdeterminants.o

# target to build an object file
SHCIgetdeterminants.cpp.o:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCIgetdeterminants.cpp.o
.PHONY : SHCIgetdeterminants.cpp.o

SHCIgetdeterminants.i: SHCIgetdeterminants.cpp.i

.PHONY : SHCIgetdeterminants.i

# target to preprocess a source file
SHCIgetdeterminants.cpp.i:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCIgetdeterminants.cpp.i
.PHONY : SHCIgetdeterminants.cpp.i

SHCIgetdeterminants.s: SHCIgetdeterminants.cpp.s

.PHONY : SHCIgetdeterminants.s

# target to generate assembly for a file
SHCIgetdeterminants.cpp.s:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCIgetdeterminants.cpp.s
.PHONY : SHCIgetdeterminants.cpp.s

SHCImakeHamiltonian.o: SHCImakeHamiltonian.cpp.o

.PHONY : SHCImakeHamiltonian.o

# target to build an object file
SHCImakeHamiltonian.cpp.o:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCImakeHamiltonian.cpp.o
.PHONY : SHCImakeHamiltonian.cpp.o

SHCImakeHamiltonian.i: SHCImakeHamiltonian.cpp.i

.PHONY : SHCImakeHamiltonian.i

# target to preprocess a source file
SHCImakeHamiltonian.cpp.i:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCImakeHamiltonian.cpp.i
.PHONY : SHCImakeHamiltonian.cpp.i

SHCImakeHamiltonian.s: SHCImakeHamiltonian.cpp.s

.PHONY : SHCImakeHamiltonian.s

# target to generate assembly for a file
SHCImakeHamiltonian.cpp.s:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCImakeHamiltonian.cpp.s
.PHONY : SHCImakeHamiltonian.cpp.s

SHCIrdm.o: SHCIrdm.cpp.o

.PHONY : SHCIrdm.o

# target to build an object file
SHCIrdm.cpp.o:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCIrdm.cpp.o
.PHONY : SHCIrdm.cpp.o

SHCIrdm.i: SHCIrdm.cpp.i

.PHONY : SHCIrdm.i

# target to preprocess a source file
SHCIrdm.cpp.i:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCIrdm.cpp.i
.PHONY : SHCIrdm.cpp.i

SHCIrdm.s: SHCIrdm.cpp.s

.PHONY : SHCIrdm.s

# target to generate assembly for a file
SHCIrdm.cpp.s:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCIrdm.cpp.s
.PHONY : SHCIrdm.cpp.s

SHCIsampledeterminants.o: SHCIsampledeterminants.cpp.o

.PHONY : SHCIsampledeterminants.o

# target to build an object file
SHCIsampledeterminants.cpp.o:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCIsampledeterminants.cpp.o
.PHONY : SHCIsampledeterminants.cpp.o

SHCIsampledeterminants.i: SHCIsampledeterminants.cpp.i

.PHONY : SHCIsampledeterminants.i

# target to preprocess a source file
SHCIsampledeterminants.cpp.i:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCIsampledeterminants.cpp.i
.PHONY : SHCIsampledeterminants.cpp.i

SHCIsampledeterminants.s: SHCIsampledeterminants.cpp.s

.PHONY : SHCIsampledeterminants.s

# target to generate assembly for a file
SHCIsampledeterminants.cpp.s:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCIsampledeterminants.cpp.s
.PHONY : SHCIsampledeterminants.cpp.s

SHCIshm.o: SHCIshm.cpp.o

.PHONY : SHCIshm.o

# target to build an object file
SHCIshm.cpp.o:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCIshm.cpp.o
.PHONY : SHCIshm.cpp.o

SHCIshm.i: SHCIshm.cpp.i

.PHONY : SHCIshm.i

# target to preprocess a source file
SHCIshm.cpp.i:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCIshm.cpp.i
.PHONY : SHCIshm.cpp.i

SHCIshm.s: SHCIshm.cpp.s

.PHONY : SHCIshm.s

# target to generate assembly for a file
SHCIshm.cpp.s:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/SHCIshm.cpp.s
.PHONY : SHCIshm.cpp.s

input.o: input.cpp.o

.PHONY : input.o

# target to build an object file
input.cpp.o:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/input.cpp.o
.PHONY : input.cpp.o

input.i: input.cpp.i

.PHONY : input.i

# target to preprocess a source file
input.cpp.i:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/input.cpp.i
.PHONY : input.cpp.i

input.s: input.cpp.s

.PHONY : input.s

# target to generate assembly for a file
input.cpp.s:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/input.cpp.s
.PHONY : input.cpp.s

integral.o: integral.cpp.o

.PHONY : integral.o

# target to build an object file
integral.cpp.o:
	$(MAKE) -f CMakeFiles/test_determinants.dir/build.make CMakeFiles/test_determinants.dir/integral.cpp.o
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/integral.cpp.o
.PHONY : integral.cpp.o

integral.i: integral.cpp.i

.PHONY : integral.i

# target to preprocess a source file
integral.cpp.i:
	$(MAKE) -f CMakeFiles/test_determinants.dir/build.make CMakeFiles/test_determinants.dir/integral.cpp.i
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/integral.cpp.i
.PHONY : integral.cpp.i

integral.s: integral.cpp.s

.PHONY : integral.s

# target to generate assembly for a file
integral.cpp.s:
	$(MAKE) -f CMakeFiles/test_determinants.dir/build.make CMakeFiles/test_determinants.dir/integral.cpp.s
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/integral.cpp.s
.PHONY : integral.cpp.s

staticVariables.o: staticVariables.cpp.o

.PHONY : staticVariables.o

# target to build an object file
staticVariables.cpp.o:
	$(MAKE) -f CMakeFiles/test_determinants.dir/build.make CMakeFiles/test_determinants.dir/staticVariables.cpp.o
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/staticVariables.cpp.o
.PHONY : staticVariables.cpp.o

staticVariables.i: staticVariables.cpp.i

.PHONY : staticVariables.i

# target to preprocess a source file
staticVariables.cpp.i:
	$(MAKE) -f CMakeFiles/test_determinants.dir/build.make CMakeFiles/test_determinants.dir/staticVariables.cpp.i
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/staticVariables.cpp.i
.PHONY : staticVariables.cpp.i

staticVariables.s: staticVariables.cpp.s

.PHONY : staticVariables.s

# target to generate assembly for a file
staticVariables.cpp.s:
	$(MAKE) -f CMakeFiles/test_determinants.dir/build.make CMakeFiles/test_determinants.dir/staticVariables.cpp.s
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/staticVariables.cpp.s
.PHONY : staticVariables.cpp.s

symmetry.o: symmetry.cpp.o

.PHONY : symmetry.o

# target to build an object file
symmetry.cpp.o:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/symmetry.cpp.o
.PHONY : symmetry.cpp.o

symmetry.i: symmetry.cpp.i

.PHONY : symmetry.i

# target to preprocess a source file
symmetry.cpp.i:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/symmetry.cpp.i
.PHONY : symmetry.cpp.i

symmetry.s: symmetry.cpp.s

.PHONY : symmetry.s

# target to generate assembly for a file
symmetry.cpp.s:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/symmetry.cpp.s
.PHONY : symmetry.cpp.s

unittests/test_determinants.o: unittests/test_determinants.cpp.o

.PHONY : unittests/test_determinants.o

# target to build an object file
unittests/test_determinants.cpp.o:
	$(MAKE) -f CMakeFiles/test_determinants.dir/build.make CMakeFiles/test_determinants.dir/unittests/test_determinants.cpp.o
.PHONY : unittests/test_determinants.cpp.o

unittests/test_determinants.i: unittests/test_determinants.cpp.i

.PHONY : unittests/test_determinants.i

# target to preprocess a source file
unittests/test_determinants.cpp.i:
	$(MAKE) -f CMakeFiles/test_determinants.dir/build.make CMakeFiles/test_determinants.dir/unittests/test_determinants.cpp.i
.PHONY : unittests/test_determinants.cpp.i

unittests/test_determinants.s: unittests/test_determinants.cpp.s

.PHONY : unittests/test_determinants.s

# target to generate assembly for a file
unittests/test_determinants.cpp.s:
	$(MAKE) -f CMakeFiles/test_determinants.dir/build.make CMakeFiles/test_determinants.dir/unittests/test_determinants.cpp.s
.PHONY : unittests/test_determinants.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... test_determinants"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousMemCheck"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalTest"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... edit_cache"
	@echo "... NightlyTest"
	@echo "... Experimental"
	@echo "... eigen_project"
	@echo "... ContinuousBuild"
	@echo "... Continuous"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyBuild"
	@echo "... ExperimentalUpdate"
	@echo "... ContinuousConfigure"
	@echo "... Dice"
	@echo "... NightlyStart"
	@echo "... NightlyUpdate"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalCoverage"
	@echo "... NightlyMemCheck"
	@echo "... ContinuousStart"
	@echo "... NightlySubmit"
	@echo "... ContinuousCoverage"
	@echo "... Nightly"
	@echo "... NightlyConfigure"
	@echo "... ExperimentalStart"
	@echo "... Davidson.o"
	@echo "... Davidson.i"
	@echo "... Davidson.s"
	@echo "... Determinants.o"
	@echo "... Determinants.i"
	@echo "... Determinants.s"
	@echo "... LCC.o"
	@echo "... LCC.i"
	@echo "... LCC.s"
	@echo "... SHCI.o"
	@echo "... SHCI.i"
	@echo "... SHCI.s"
	@echo "... SHCISortMpiUtils.o"
	@echo "... SHCISortMpiUtils.i"
	@echo "... SHCISortMpiUtils.s"
	@echo "... SHCIbasics.o"
	@echo "... SHCIbasics.i"
	@echo "... SHCIbasics.s"
	@echo "... SHCIgetdeterminants.o"
	@echo "... SHCIgetdeterminants.i"
	@echo "... SHCIgetdeterminants.s"
	@echo "... SHCImakeHamiltonian.o"
	@echo "... SHCImakeHamiltonian.i"
	@echo "... SHCImakeHamiltonian.s"
	@echo "... SHCIrdm.o"
	@echo "... SHCIrdm.i"
	@echo "... SHCIrdm.s"
	@echo "... SHCIsampledeterminants.o"
	@echo "... SHCIsampledeterminants.i"
	@echo "... SHCIsampledeterminants.s"
	@echo "... SHCIshm.o"
	@echo "... SHCIshm.i"
	@echo "... SHCIshm.s"
	@echo "... input.o"
	@echo "... input.i"
	@echo "... input.s"
	@echo "... integral.o"
	@echo "... integral.i"
	@echo "... integral.s"
	@echo "... staticVariables.o"
	@echo "... staticVariables.i"
	@echo "... staticVariables.s"
	@echo "... symmetry.o"
	@echo "... symmetry.i"
	@echo "... symmetry.s"
	@echo "... unittests/test_determinants.o"
	@echo "... unittests/test_determinants.i"
	@echo "... unittests/test_determinants.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

